name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.9.2

  riverpod_generator: ^4.0.0+1

  dio: ^5.9.0
  isar: ^3.1.0+1
  formz: ^0.8.0
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_riverpod: ^3.1.0
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
